//
// MIT license
// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: MIT
//

//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//

#ifndef GGML_SYCL_PRESETS_HPP  // 如果未定义 GGML_SYCL_PRESETS_HPP 则编译
#define GGML_SYCL_PRESETS_HPP  // 宏定义 GGML_SYCL_PRESETS_HPP

#define GGML_SYCL_MAX_STREAMS       8  // 宏定义 GGML_SYCL_MAX_STREAMS
#define GGML_SYCL_MAX_BUFFERS       256  // 宏定义 GGML_SYCL_MAX_BUFFERS

#define WARP_SIZE GGML_SYCL_WARP_SIZE  // 宏定义 WARP_SIZE
#define MATRIX_ROW_PADDING 512 // last row of quant. matrices is a multiple of this to avoid out-of-bounds memory accesses  // 宏定义 MATRIX_ROW_PADDING

#define SYCL_GELU_BLOCK_SIZE 256  // 宏定义 SYCL_GELU_BLOCK_SIZE
#define SYCL_SILU_BLOCK_SIZE 256  // 宏定义 SYCL_SILU_BLOCK_SIZE
#define SYCL_TANH_BLOCK_SIZE 256  // 宏定义 SYCL_TANH_BLOCK_SIZE
#define SYCL_RELU_BLOCK_SIZE 256  // 宏定义 SYCL_RELU_BLOCK_SIZE
#define SYCL_HARDSIGMOID_BLOCK_SIZE 256  // 宏定义 SYCL_HARDSIGMOID_BLOCK_SIZE
#define SYCL_HARDSWISH_BLOCK_SIZE 256  // 宏定义 SYCL_HARDSWISH_BLOCK_SIZE
#define SYCL_EXP_BLOCK_SIZE 256  // 宏定义 SYCL_EXP_BLOCK_SIZE
#define SYCL_NEG_BLOCK_SIZE 256  // 宏定义 SYCL_NEG_BLOCK_SIZE
#define SYCL_SIGMOID_BLOCK_SIZE 256  // 宏定义 SYCL_SIGMOID_BLOCK_SIZE
#define SYCL_SQRT_BLOCK_SIZE 256  // 宏定义 SYCL_SQRT_BLOCK_SIZE
#define SYCL_SIN_BLOCK_SIZE 256  // 宏定义 SYCL_SIN_BLOCK_SIZE
#define SYCL_SQR_BLOCK_SIZE 256  // 宏定义 SYCL_SQR_BLOCK_SIZE
#define SYCL_SET_BLOCK_SIZE 256  // 宏定义 SYCL_SET_BLOCK_SIZE
#define SYCL_CPY_BLOCK_SIZE 32  // 宏定义 SYCL_CPY_BLOCK_SIZE
#define SYCL_SCALE_BLOCK_SIZE 256  // 宏定义 SYCL_SCALE_BLOCK_SIZE
#define SYCL_CLAMP_BLOCK_SIZE 256  // 宏定义 SYCL_CLAMP_BLOCK_SIZE
#define SYCL_ROPE_BLOCK_SIZE 256  // 宏定义 SYCL_ROPE_BLOCK_SIZE
#define SYCL_ALIBI_BLOCK_SIZE 32  // 宏定义 SYCL_ALIBI_BLOCK_SIZE
#define SYCL_DIAG_MASK_INF_BLOCK_SIZE 32  // 宏定义 SYCL_DIAG_MASK_INF_BLOCK_SIZE
#define SYCL_QUANTIZE_BLOCK_SIZE 256  // 宏定义 SYCL_QUANTIZE_BLOCK_SIZE
#define SYCL_DEQUANTIZE_BLOCK_SIZE 256  // 宏定义 SYCL_DEQUANTIZE_BLOCK_SIZE
#define SYCL_GET_ROWS_BLOCK_SIZE 256  // 宏定义 SYCL_GET_ROWS_BLOCK_SIZE
#define SYCL_UPSCALE_BLOCK_SIZE 256  // 宏定义 SYCL_UPSCALE_BLOCK_SIZE
#define SYCL_CONCAT_BLOCK_SIZE 256  // 宏定义 SYCL_CONCAT_BLOCK_SIZE
#define SYCL_PAD_BLOCK_SIZE 256  // 宏定义 SYCL_PAD_BLOCK_SIZE
#define SYCL_ACC_BLOCK_SIZE 256  // 宏定义 SYCL_ACC_BLOCK_SIZE
#define SYCL_IM2COL_BLOCK_SIZE 256  // 宏定义 SYCL_IM2COL_BLOCK_SIZE
#define SYCL_POOL2D_BLOCK_SIZE 256  // 宏定义 SYCL_POOL2D_BLOCK_SIZE
#define SYCL_ARGMAX_BLOCK_SIZE 256  // 宏定义 SYCL_ARGMAX_BLOCK_SIZE
#define SYCL_CONV_TRANPOSE_1D_BLOCK_SIZE 256  // 宏定义 SYCL_CONV_TRANPOSE_1D_BLOCK_SIZE
#define SYCL_TIMESTEP_EMBEDDING_BLOCK_SIZE 256  // 宏定义 SYCL_TIMESTEP_EMBEDDING_BLOCK_SIZE
#define SYCL_ARANGE_BLOCK_SIZE 256  // 宏定义 SYCL_ARANGE_BLOCK_SIZE

// dmmv = dequantize_mul_mat_vec
#ifndef GGML_SYCL_DMMV_X  // 如果未定义 GGML_SYCL_DMMV_X 则编译
#define GGML_SYCL_DMMV_X 32  // 宏定义 GGML_SYCL_DMMV_X
#endif  // 条件编译结束
#ifndef GGML_SYCL_MMV_Y  // 如果未定义 GGML_SYCL_MMV_Y 则编译
#define GGML_SYCL_MMV_Y 1  // 宏定义 GGML_SYCL_MMV_Y
#endif  // 条件编译结束

#ifndef K_QUANTS_PER_ITERATION  // 如果未定义 K_QUANTS_PER_ITERATION 则编译
#define K_QUANTS_PER_ITERATION 2  // 宏定义 K_QUANTS_PER_ITERATION
#else  // 否则
static_assert(K_QUANTS_PER_ITERATION == 1 || K_QUANTS_PER_ITERATION == 2, "K_QUANTS_PER_ITERATION must be 1 or 2");
#endif  // 条件编译结束

#ifndef GGML_SYCL_PEER_MAX_BATCH_SIZE  // 如果未定义 GGML_SYCL_PEER_MAX_BATCH_SIZE 则编译
#define GGML_SYCL_PEER_MAX_BATCH_SIZE 128  // 宏定义 GGML_SYCL_PEER_MAX_BATCH_SIZE
#endif // GGML_SYCL_PEER_MAX_BATCH_SIZE  // 条件编译结束

#define MUL_MAT_SRC1_COL_STRIDE 128  // 宏定义 MUL_MAT_SRC1_COL_STRIDE

#define QK_WARP_SIZE 32  // 宏定义 QK_WARP_SIZE
#define WARP_32_SIZE 32  // 宏定义 WARP_32_SIZE
#define WARP_16_SIZE 16  // 宏定义 WARP_16_SIZE

#endif // GGML_SYCL_PRESETS_HPP  // 条件编译结束
